### ISSUE TITLE
addstream: object krijgt geen control metadata

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/DtlUpdater#1]
Er werden bij heel wat objecten een VIEW_MAIN manifestation aan een ARCHIVE gekoppeld via addStream. Bij alle objecten is de update gelukt, maar één object is er geen controle metadata gekopieerd van het ARCHIVE object. De log file geen geen foutmelding en toont alles normaal. De nieuwe manifestation werd ook toegevoegd. Enkel de control metadata ontbreekt (archive heeft control metadata)

logfile: DtlUpdater/addStream.log.20110713091801

VIEW_MAIN: pid:795736   label:19150102
ARCHIVE: pid:795173     label:19150102

**Comment by samalloing** [comment]
De update opnieuw uitvoeren is wel gelukt, maar misschien kan de logging geupdatet worden zodat dit probleem zichtbaar wordt

**Comment by Kris-LIBIS** [comment]
TODO: detectie van fouten verbeteren + logging uitbreiden
