### ISSUE TITLE
addStream: fout wordt gemeld, maar toevoegen object is gelukt

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/DtlUpdater#2]
Na het succesvol toevoegen van een stream aan een object (Complex krijgt een pdf manifestation), wordt er een bijkomende query uitgevoerd die misloopt. De addstream is wel gelukt.

I,22,[2011-08-02 09:03:11.977],Adding stream '/nas/vol01/kadoc/20101210/BE-94285
5-1504-2.pdf' as 'VIEW' to pid 802873,AddStream,AddStreamWorker
I,35,[2011-08-02 09:03:16.381],SUCCESS: AddStream '/nas/vol01/kadoc/20101210/BE-
942855-1504-2.pdf' 'VIEW' : existing object: 802873 new object: 803360,AddStream
,AddStreamWorker

....

E,46,[2011-08-02 09:03:22.390],Could not find any object with label: '802873 ++ 
803360' and usage type: 'VIEW',AddStream,AddStreamWorker
I,47,[2011-08-02 09:03:22.393],FAILURE: AddStream of '802873 ++ 803360' & 'VIEW'
 did not succeed,AddStream,AddStreamWorker

logfile: DtlUpdater/oudeLogbestanden/addStream.log.20110802090217

**Comment by Kris-LIBIS** [comment]
Ja dat is een gekend probleem met de web services van Digitool. Het kan namelijk gebeuren dat een query kort na een update geen resultaat geeft. Ik weet niet precies waarom die query nog uitgevoerd werd; misschien gewoon om te checken, misschien om nog een update te doen aan de metadata records?

Ik weet ook niet wat ik er aan kan doen. Het kan soms wel minuten duren vooraleer een nieuw object kan worden gevonden, maar dikwijls is het nieuwe object onmiddelijk beschikbaar.

**Comment by samalloing** [comment]
Nee het is een foutje van mij. ik had teveel gekopieerd en de pidDumpfile was ook mijn inputfile. Ik denk dat dat de reden was van de extra queries.
Het probleem dat je vermeldt van het pas na een tijd beschikbaar worden, is omdat de com.exlibris.digitool.repository.jobs.TransactionSynchronizerJob moet uitgevoerd worden. Als dat gebeurd is, dan is de metadata beschikbaar. Deze job wordt automatisch om de x seconden uitgevoerd.
